---
 - name: Accessing Complex Variable Data
   hosts: srv1
   user: vagrant
   become: True
   become_method: sudo
   gather_facts: True
#   vars: 
#      nodename:  {{ ansible_hostname }}
#   ignore_errors: True
   tasks:
     - name: print the ipv4 address of each node
       debug: msg="{{ ansible_hostname }} ipv4 address {{ ansible_eth1["ipv4"]["address"] }} "
 
     - name: print the nodename of each name from fact variable {{ ansible_eth1.ipv4.address }}
       debug: msg="{{ ansible_nodename }} for  {{ ansible_eth1["ipv4"]["address"] }}  "
     
     
     
    
