---
 - hosts: srv1
   user: vagrant
   become: yes
   gather_facts: False
   become_method: sudo 
   tasks:
     - name: Stop Apache Service
       service: name=apache2
                state=stopped
       notify:
         - start uninstall _apache
    
   handlers:
     - name: start uninstall _apache
       apt: pkg=apache2
            state=absent
            update_cache=true 
