---
 - hosts: srv1
   user: vagrant
   become: yes
   gather_facts: False
   become_method: sudo 
   tasks:
     - name: Install Apache
       apt: pkg=apache2
            state=present
            update_cache=true
       notify: 
         - start update
    
   handlers: 
     - name: start update
       service: name=apache2
                state=started
 
