- name: show return value of command module
  hosts: srv1
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login
    - debug: var=login.stdout
    - debug: var=login.stdout_lines
    - debug: msg="Logged in as user {{ login.stdout }}"
